### ISSUE TITLE
Unhandled Exception bei Eingabe zu hoher Werte für -et

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#125]
Wenn zu hohe Werte für -et eingegeben werden, stürzt ProcDumpEx aktuell ab. Höhere Werte als 24,8 Tage funktionieren aber.

Folgende Parameter wurden verwendet für den Test:

_procdumpex.exe -ma -e -w -et "10675100d0h0m0s" -pn "<Prozessname>.exe"_

Dabei erhalten wir folgende Exception:

```
Unhandled exception. System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime. (Parameter 't')
   at System.DateTime.ThrowDateArithmetic(Int32 param)
   at System.DateTime.op_Addition(DateTime d, TimeSpan t)
   at ProcDumpEx.ThreadingTimer.Start()
   at ProcDumpEx.ProcDumpExCommand.RunAsync()
   at ProcDumpEx.ProcDumpEx.RunAsync()
   at ProcDumpEx.Program.Main(String[] args)
   at ProcDumpEx.Program.<Main>(String[] args)
```

Mir ist bewusst, das diese Zahlenwerte in der Realität nie verwendet werden würden, aber wir sollten das trotzdem korrekt abfangen :)

**Comment by PoppyTheDeveloPaw** [comment]
Gefixt mit #126
