### ISSUE TITLE
Unhandled Exception bei Verwendung von -pn und -inf in der falschen Reihenfolge

### ISSUE THREAD

**Issue by Zocoya** [PoppyTheDeveloPaw/ProcDumpEx#48]
Ich weiß das ich -pn und -inf vertauscht habe, aber hier sollten wir etwas am Exception Handling machen. Ich habe folgende Parameter verwendet:

procdumpex.exe -ma -pn -inf "application1.exe"

Und erhalte daraufhin folgende Exception

Unhandled exception. ProcDumpEx.Exceptions.ValueExpectedException: For the option -pn one or more values are expected
   at ProcDumpEx.ProcDumpExCommandParser.ParseAndRemoveOptionValueIfExists(Type type, CommandSplitList tokens) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcDumpExCommandParser.cs:line 88
   at ProcDumpEx.ProcDumpExCommandParser.ParseAndRemoveOptionValueIfExists[TReturnValue](CommandSplitList tokens) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcDumpExCommandParser.cs:line 107
   at ProcDumpEx.ProcDumpExCommandParser.ExtractProcesses(CommandSplitList tokens) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcDumpExCommandParser.cs:line 50
   at ProcDumpEx.ProcDumpExCommandParser.Parse(String commandLine, Int32 logId) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ProcDumpExCommandParser.cs:line 24
   at ProcDumpEx.code.ArgumentManager.GetCommands(String[] args) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\ArgumentManager.cs:line 47
   at Program.<Main>$(String[] args) in C:\Users\alexa\Documents\GitHub\ProcDumpEx\code\Program.cs:line 19
   at Program.<Main>(String[] args)

**Comment by Zocoya** [comment]
Ist zwar unnötig es zu erwähnen, aber Parameter -log greift dann natürlich auch nicht mehr :D

**Comment by PoppyTheDeveloPaw** [comment]
Behoben mit #61
